- ดูไฟล์ที่ import มาให้ ให้ลบสิ่งที่ซ้ำซ้อน และทำสิ่งที่ควรจะเป็น
- run lint ใน package.json และแก้ไข error ทั้งหมดโดยไม่มีเหลือ
- ควร refactor อะไรไปใช้ composables หรือ components บ้าง
- ควรทำอย่างไร