import UnoCSS from "@unocss/vite";
webpack: "logos:webpack",
    deno: "vscode-icons:file-type-deno",
        vite: "logos:vitejs",
            esbuild: "logos:esbuild",
                powershell: "vscode-icons:file-type-powershell",
                    "uno.config.ts": "logos:unocss",
                        turbo: "vscode-icons:file-type-turbo",
                            "biome.json": "devicon:biome",
                                vscode: "devicon:vscode",
                                    vitest: "logos:vitest",
                                        tailwind: "logos:tailwindcss",
                                            terminal: "logos:terminal",
                                                git: "logos:git-icon",
                                                    ".gitconfig": "logos:git-icon",
                                                        ".gitignore": "logos:git-icon",
            },
        }),

    ],
});
